"""Initial database schema with lowercase enums

Revision ID: 2328fe36a57f
Revises: 
Create Date: 2025-06-30 17:37:20.236815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2328fe36a57f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('content_directions', sa.Text(), nullable=False),
    sa.Column('output_format', sa.Enum('BLOG_POST', 'BOOK_CHAPTER', 'RESEARCH_REPORT', 'INTERACTIVE_SESSION', name='outputformatenum'), nullable=False),
    sa.Column('target_audience', sa.Enum('GENERAL_PUBLIC', 'CYBERSECURITY_PROFESSIONALS', 'STUDENTS', 'EXECUTIVES', 'TECHNICAL_TEAMS', name='targetaudienceenum'), nullable=False),
    sa.Column('technical_depth', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='technicaldepthenum'), nullable=False),
    sa.Column('include_historical_context', sa.Boolean(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('confidentiality', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'INITIALIZING', 'RESEARCHING', 'ANALYZING', 'GENERATING', 'COMPLETED', 'FAILED', name='researchstatusenum'), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_sessions_id'), 'research_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_research_sessions_session_id'), 'research_sessions', ['session_id'], unique=True)
    op.create_table('research_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('agent_contributions', sa.JSON(), nullable=True),
    sa.Column('output_format', sa.Enum('BLOG_POST', 'BOOK_CHAPTER', 'RESEARCH_REPORT', 'INTERACTIVE_SESSION', name='outputformatenum'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_concepts', sa.JSON(), nullable=True),
    sa.Column('exercises', sa.JSON(), nullable=True),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_results_id'), 'research_results', ['id'], unique=False)
    op.create_index(op.f('ix_research_results_result_id'), 'research_results', ['result_id'], unique=True)
    op.create_table('research_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['research_results.result_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_metadata_id'), 'research_metadata', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_metadata_id'), table_name='research_metadata')
    op.drop_table('research_metadata')
    op.drop_index(op.f('ix_research_results_result_id'), table_name='research_results')
    op.drop_index(op.f('ix_research_results_id'), table_name='research_results')
    op.drop_table('research_results')
    op.drop_index(op.f('ix_research_sessions_session_id'), table_name='research_sessions')
    op.drop_index(op.f('ix_research_sessions_id'), table_name='research_sessions')
    op.drop_table('research_sessions')
    # ### end Alembic commands ###
