"""Add technical_metadata column to research_results

Revision ID: 8dbc29d3e3ba
Revises: 2328fe36a57f
Create Date: 2025-06-30 18:23:08.876167

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8dbc29d3e3ba"
down_revision: Union[str, Sequence[str], None] = "2328fe36a57f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("research_results", sa.Column("technical_metadata", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("research_results", "technical_metadata")
    # ### end Alembic commands ###
