"""Add agent activity tracking and enhanced workflow metadata

Revision ID: e3b3aa1bbba9
Revises: 8dbc29d3e3ba
Create Date: 2025-06-30 21:05:43.763012

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e3b3aa1bbba9"
down_revision: Union[str, Sequence[str], None] = "8dbc29d3e3ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # agent_activities table already exists, skip creation

    # Add workflow metadata columns to research_results
    op.add_column("research_results", sa.Column("workflow_metadata", sa.JSON(), nullable=True))
    op.add_column("research_results", sa.Column("generation_process", sa.JSON(), nullable=True))
    op.add_column("research_results", sa.Column("agent_workflow_summary", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop workflow metadata columns from research_results
    op.drop_column("research_results", "agent_workflow_summary")
    op.drop_column("research_results", "generation_process")
    op.drop_column("research_results", "workflow_metadata")

    # Note: agent_activities table not dropped as it was created outside migration
    # ### end Alembic commands ###
